#!/usr/bin/php
<? # vim: ft=php

  require dirname(__FILE__).'/../config/environment.php';
  require LIB.'tests.php';

  $tests = array(
    'controller',
    'helper',
    'model',
    'view',
  );

  if (is_dir(TEST.'framework')) {
    array_push($tests, 'framework');
  }

  if (in_array($argv[1], $tests)) {
    $dirs = $argv[1];
  } elseif (empty($argv[1])) {
    $dirs = $tests;
  } else {
    print "Usage: $argv[0] [";
    print implode("|", $tests);
    print "]\n";
    exit(255);
  }

  print "\n";
  array_map(run_tests, (array) $dirs);

?>
